name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build and analyze
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: sonarsource/sonarqube-scan-action@v6
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://localhost:9000
